// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (tenant_id, actor_user_id, action, booking_id, service_id, staff_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditLogParams struct {
	TenantID    uuid.UUID
	ActorUserID pgtype.UUID
	Action      string
	BookingID   pgtype.UUID
	ServiceID   pgtype.UUID
	StaffID     pgtype.UUID
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.TenantID,
		arg.ActorUserID,
		arg.Action,
		arg.BookingID,
		arg.ServiceID,
		arg.StaffID,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT a.id, a.action, a.created_at, u.email AS actor_email,
       b.customer_name AS booking_customer, b.starts_at AS booking_starts_at,
       s.name AS service_name, st.name AS staff_name
  FROM audit_log a
  LEFT JOIN users u ON u.tenant_id = a.tenant_id AND u.id = a.actor_user_id
  LEFT JOIN bookings b ON b.tenant_id = a.tenant_id AND b.id = a.booking_id
  LEFT JOIN services s ON s.tenant_id = a.tenant_id AND s.id = a.service_id
  LEFT JOIN staff st ON st.tenant_id = a.tenant_id AND st.id = a.staff_id
 ORDER BY a.created_at DESC, a.id DESC
 LIMIT $1
`

type ListAuditLogRow struct {
	ID              uuid.UUID
	Action          string
	CreatedAt       time.Time
	ActorEmail      pgtype.Text
	BookingCustomer pgtype.Text
	BookingStartsAt pgtype.Timestamptz
	ServiceName     pgtype.Text
	StaffName       pgtype.Text
}

// The dashboard's audit list: one row per entry with the labels the page shows,
// so no entry costs a second query. Every join is tenant-composite, and row
// level security scopes the whole statement to the caller's tenant.
func (q *Queries) ListAuditLog(ctx context.Context, rowLimit int32) ([]ListAuditLogRow, error) {
	rows, err := q.db.Query(ctx, listAuditLog, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogRow{}
	for rows.Next() {
		var i ListAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.CreatedAt,
			&i.ActorEmail,
			&i.BookingCustomer,
			&i.BookingStartsAt,
			&i.ServiceName,
			&i.StaffName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
