// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: availability.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activeStaffForSlotSearch = `-- name: ActiveStaffForSlotSearch :many
SELECT id, tenant_id, name, email, active
  FROM staff
 WHERE active
 ORDER BY name, id
`

type ActiveStaffForSlotSearchRow struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Name     string
	Email    string
	Active   bool
}

func (q *Queries) ActiveStaffForSlotSearch(ctx context.Context) ([]ActiveStaffForSlotSearchRow, error) {
	rows, err := q.db.Query(ctx, activeStaffForSlotSearch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActiveStaffForSlotSearchRow{}
	for rows.Next() {
		var i ActiveStaffForSlotSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Email,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const busyForSlotSearch = `-- name: BusyForSlotSearch :many
SELECT staff_id, starts_at, ends_at
  FROM bookings
 WHERE status = 'confirmed'
   AND starts_at < $1
   AND ends_at > $2
 ORDER BY staff_id, starts_at, id
`

type BusyForSlotSearchParams struct {
	RangeEnd   time.Time
	RangeStart time.Time
}

type BusyForSlotSearchRow struct {
	StaffID  uuid.UUID
	StartsAt time.Time
	EndsAt   time.Time
}

func (q *Queries) BusyForSlotSearch(ctx context.Context, arg BusyForSlotSearchParams) ([]BusyForSlotSearchRow, error) {
	rows, err := q.db.Query(ctx, busyForSlotSearch, arg.RangeEnd, arg.RangeStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusyForSlotSearchRow{}
	for rows.Next() {
		var i BusyForSlotSearchRow
		if err := rows.Scan(&i.StaffID, &i.StartsAt, &i.EndsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTimeOffForStaff = `-- name: DeleteTimeOffForStaff :execrows
DELETE FROM time_off
 WHERE staff_id = $1 AND id = $2
`

type DeleteTimeOffForStaffParams struct {
	StaffID uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) DeleteTimeOffForStaff(ctx context.Context, arg DeleteTimeOffForStaffParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTimeOffForStaff, arg.StaffID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWeeklyRulesForStaff = `-- name: DeleteWeeklyRulesForStaff :exec
DELETE FROM availability_rules
 WHERE staff_id = $1
`

func (q *Queries) DeleteWeeklyRulesForStaff(ctx context.Context, staffID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWeeklyRulesForStaff, staffID)
	return err
}

const insertTimeOff = `-- name: InsertTimeOff :one
INSERT INTO time_off (tenant_id, staff_id, starts_at, ends_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertTimeOffParams struct {
	TenantID uuid.UUID
	StaffID  uuid.UUID
	StartsAt time.Time
	EndsAt   time.Time
}

func (q *Queries) InsertTimeOff(ctx context.Context, arg InsertTimeOffParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertTimeOff,
		arg.TenantID,
		arg.StaffID,
		arg.StartsAt,
		arg.EndsAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertWeeklyRule = `-- name: InsertWeeklyRule :exec
INSERT INTO availability_rules (tenant_id, staff_id, weekday, start_minute, end_minute)
VALUES ($1, $2, $3, $4, $5)
`

type InsertWeeklyRuleParams struct {
	TenantID    uuid.UUID
	StaffID     uuid.UUID
	Weekday     int16
	StartMinute int32
	EndMinute   int32
}

func (q *Queries) InsertWeeklyRule(ctx context.Context, arg InsertWeeklyRuleParams) error {
	_, err := q.db.Exec(ctx, insertWeeklyRule,
		arg.TenantID,
		arg.StaffID,
		arg.Weekday,
		arg.StartMinute,
		arg.EndMinute,
	)
	return err
}

const listTimeOffForStaff = `-- name: ListTimeOffForStaff :many
SELECT id, staff_id, starts_at, ends_at
  FROM time_off
 WHERE staff_id = $1
 ORDER BY starts_at, id
`

type ListTimeOffForStaffRow struct {
	ID       uuid.UUID
	StaffID  uuid.UUID
	StartsAt time.Time
	EndsAt   time.Time
}

func (q *Queries) ListTimeOffForStaff(ctx context.Context, staffID uuid.UUID) ([]ListTimeOffForStaffRow, error) {
	rows, err := q.db.Query(ctx, listTimeOffForStaff, staffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimeOffForStaffRow{}
	for rows.Next() {
		var i ListTimeOffForStaffRow
		if err := rows.Scan(
			&i.ID,
			&i.StaffID,
			&i.StartsAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeeklyRulesForStaff = `-- name: ListWeeklyRulesForStaff :many
SELECT weekday, start_minute, end_minute
  FROM availability_rules
 WHERE staff_id = $1
 ORDER BY weekday, start_minute, end_minute
`

type ListWeeklyRulesForStaffRow struct {
	Weekday     int16
	StartMinute int32
	EndMinute   int32
}

func (q *Queries) ListWeeklyRulesForStaff(ctx context.Context, staffID uuid.UUID) ([]ListWeeklyRulesForStaffRow, error) {
	rows, err := q.db.Query(ctx, listWeeklyRulesForStaff, staffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWeeklyRulesForStaffRow{}
	for rows.Next() {
		var i ListWeeklyRulesForStaffRow
		if err := rows.Scan(&i.Weekday, &i.StartMinute, &i.EndMinute); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStaff = `-- name: LockStaff :one
SELECT 1 AS visible FROM staff WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockStaff(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, lockStaff, id)
	var visible int32
	err := row.Scan(&visible)
	return visible, err
}

const rulesForSlotSearch = `-- name: RulesForSlotSearch :many
SELECT staff_id, weekday, start_minute, end_minute
  FROM availability_rules
 ORDER BY staff_id, weekday, start_minute, end_minute
`

type RulesForSlotSearchRow struct {
	StaffID     uuid.UUID
	Weekday     int16
	StartMinute int32
	EndMinute   int32
}

func (q *Queries) RulesForSlotSearch(ctx context.Context) ([]RulesForSlotSearchRow, error) {
	rows, err := q.db.Query(ctx, rulesForSlotSearch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RulesForSlotSearchRow{}
	for rows.Next() {
		var i RulesForSlotSearchRow
		if err := rows.Scan(
			&i.StaffID,
			&i.Weekday,
			&i.StartMinute,
			&i.EndMinute,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serviceForSlotSearch = `-- name: ServiceForSlotSearch :one
SELECT id, tenant_id, name, duration_minutes, buffer_minutes, price_cents, active
  FROM services
 WHERE id = $1 AND active
`

type ServiceForSlotSearchRow struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	Name            string
	DurationMinutes int32
	BufferMinutes   int32
	PriceCents      int32
	Active          bool
}

func (q *Queries) ServiceForSlotSearch(ctx context.Context, id uuid.UUID) (ServiceForSlotSearchRow, error) {
	row := q.db.QueryRow(ctx, serviceForSlotSearch, id)
	var i ServiceForSlotSearchRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DurationMinutes,
		&i.BufferMinutes,
		&i.PriceCents,
		&i.Active,
	)
	return i, err
}

const staffVisible = `-- name: StaffVisible :one
SELECT 1 AS visible FROM staff WHERE id = $1
`

func (q *Queries) StaffVisible(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, staffVisible, id)
	var visible int32
	err := row.Scan(&visible)
	return visible, err
}

const tenantByID = `-- name: TenantByID :one
SELECT id, slug, name, timezone
  FROM tenants
 WHERE id = $1
`

type TenantByIDRow struct {
	ID       uuid.UUID
	Slug     string
	Name     string
	Timezone string
}

func (q *Queries) TenantByID(ctx context.Context, id uuid.UUID) (TenantByIDRow, error) {
	row := q.db.QueryRow(ctx, tenantByID, id)
	var i TenantByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Timezone,
	)
	return i, err
}

const timeOffForSlotSearch = `-- name: TimeOffForSlotSearch :many
SELECT id, staff_id, starts_at, ends_at
  FROM time_off
 WHERE starts_at < $1 AND ends_at > $2
 ORDER BY staff_id, starts_at, id
`

type TimeOffForSlotSearchParams struct {
	RangeEnd   time.Time
	RangeStart time.Time
}

type TimeOffForSlotSearchRow struct {
	ID       uuid.UUID
	StaffID  uuid.UUID
	StartsAt time.Time
	EndsAt   time.Time
}

// Overlap is half-open, so a row that only touches the range edge does not count.
func (q *Queries) TimeOffForSlotSearch(ctx context.Context, arg TimeOffForSlotSearchParams) ([]TimeOffForSlotSearchRow, error) {
	rows, err := q.db.Query(ctx, timeOffForSlotSearch, arg.RangeEnd, arg.RangeStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimeOffForSlotSearchRow{}
	for rows.Next() {
		var i TimeOffForSlotSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.StaffID,
			&i.StartsAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
