// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bookingByID = `-- name: BookingByID :one
SELECT id, tenant_id, staff_id, service_id, customer_name, customer_email,
       starts_at, ends_at, status, idempotency_key, created_at
  FROM bookings
 WHERE id = $1
`

func (q *Queries) BookingByID(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, bookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StaffID,
		&i.ServiceID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const bookingByIdempotencyKey = `-- name: BookingByIdempotencyKey :one
SELECT id, tenant_id, staff_id, service_id, customer_name, customer_email,
       starts_at, ends_at, status, idempotency_key, created_at
  FROM bookings
 WHERE tenant_id = $1 AND idempotency_key = $2
`

type BookingByIdempotencyKeyParams struct {
	TenantID       uuid.UUID
	IdempotencyKey string
}

func (q *Queries) BookingByIdempotencyKey(ctx context.Context, arg BookingByIdempotencyKeyParams) (Booking, error) {
	row := q.db.QueryRow(ctx, bookingByIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StaffID,
		&i.ServiceID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const bookingMessage = `-- name: BookingMessage :one
SELECT b.id, b.tenant_id, b.staff_id, b.service_id, b.customer_name, b.customer_email,
       b.starts_at, b.ends_at, b.status, b.created_at,
       t.slug, t.name AS tenant_name, t.timezone,
       s.name AS service_name, st.name AS staff_name
  FROM bookings b
  JOIN tenants t ON t.id = b.tenant_id
  JOIN services s ON s.tenant_id = b.tenant_id AND s.id = b.service_id
  JOIN staff st ON st.tenant_id = b.tenant_id AND st.id = b.staff_id
 WHERE b.id = $1
`

type BookingMessageRow struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	StaffID       uuid.UUID
	ServiceID     uuid.UUID
	CustomerName  string
	CustomerEmail string
	StartsAt      time.Time
	EndsAt        time.Time
	Status        string
	CreatedAt     time.Time
	Slug          string
	TenantName    string
	Timezone      string
	ServiceName   string
	StaffName     string
}

func (q *Queries) BookingMessage(ctx context.Context, id uuid.UUID) (BookingMessageRow, error) {
	row := q.db.QueryRow(ctx, bookingMessage, id)
	var i BookingMessageRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StaffID,
		&i.ServiceID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.CreatedAt,
		&i.Slug,
		&i.TenantName,
		&i.Timezone,
		&i.ServiceName,
		&i.StaffName,
	)
	return i, err
}

const cancelBooking = `-- name: CancelBooking :execrows
UPDATE bookings SET status = 'cancelled' WHERE id = $1
`

// Cancelling is status-blind, so a repeat cancel still reports one row.
func (q *Queries) CancelBooking(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelBooking, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertBooking = `-- name: InsertBooking :one
INSERT INTO bookings (tenant_id, staff_id, service_id, customer_name, customer_email,
                      starts_at, ends_at, status, idempotency_key)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, 'confirmed', $8)
ON CONFLICT (tenant_id, idempotency_key) DO NOTHING
RETURNING id, tenant_id, staff_id, service_id, customer_name, customer_email,
          starts_at, ends_at, status, idempotency_key, created_at
`

type InsertBookingParams struct {
	TenantID       uuid.UUID
	StaffID        uuid.UUID
	ServiceID      uuid.UUID
	CustomerName   string
	CustomerEmail  string
	StartsAt       time.Time
	EndsAt         time.Time
	IdempotencyKey string
}

func (q *Queries) InsertBooking(ctx context.Context, arg InsertBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, insertBooking,
		arg.TenantID,
		arg.StaffID,
		arg.ServiceID,
		arg.CustomerName,
		arg.CustomerEmail,
		arg.StartsAt,
		arg.EndsAt,
		arg.IdempotencyKey,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StaffID,
		&i.ServiceID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const listBookingsInRange = `-- name: ListBookingsInRange :many
SELECT b.id, b.staff_id, b.service_id, b.customer_name, b.starts_at, b.ends_at, b.status,
       s.name AS service_name, st.name AS staff_name
  FROM bookings b
  JOIN services s ON s.tenant_id = b.tenant_id AND s.id = b.service_id
  JOIN staff st ON st.tenant_id = b.tenant_id AND st.id = b.staff_id
 WHERE b.starts_at < $1 AND b.ends_at > $2
 ORDER BY b.starts_at, b.id
`

type ListBookingsInRangeParams struct {
	RangeEnd   time.Time
	RangeStart time.Time
}

type ListBookingsInRangeRow struct {
	ID           uuid.UUID
	StaffID      uuid.UUID
	ServiceID    uuid.UUID
	CustomerName string
	StartsAt     time.Time
	EndsAt       time.Time
	Status       string
	ServiceName  string
	StaffName    string
}

// The calendar and the booking list are one query per rendered range: the
// interval test is half-open and uses the stored occupied end, so a booking
// that starts before the range and still occupies it is included. Both names
// come from the join, so a fifty-booking week costs one round trip, not fifty.
func (q *Queries) ListBookingsInRange(ctx context.Context, arg ListBookingsInRangeParams) ([]ListBookingsInRangeRow, error) {
	rows, err := q.db.Query(ctx, listBookingsInRange, arg.RangeEnd, arg.RangeStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsInRangeRow{}
	for rows.Next() {
		var i ListBookingsInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.StaffID,
			&i.ServiceID,
			&i.CustomerName,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.ServiceName,
			&i.StaffName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveStaff = `-- name: LockActiveStaff :one
SELECT 1 AS visible FROM staff WHERE id = $1 AND active FOR UPDATE
`

// The write path locks the staff row before inserting, so concurrent bookings
// for one staff member queue instead of deadlocking on the exclusion
// constraint's index. A deactivated staff member is not lockable: a booking
// would otherwise be stored for somebody who no longer takes appointments.
func (q *Queries) LockActiveStaff(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, lockActiveStaff, id)
	var visible int32
	err := row.Scan(&visible)
	return visible, err
}
