// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bookingByID = `-- name: BookingByID :one
SELECT id, tenant_id, staff_id, service_id, customer_name, customer_email,
       starts_at, ends_at, status, idempotency_key, created_at
  FROM bookings
 WHERE id = $1
`

func (q *Queries) BookingByID(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, bookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StaffID,
		&i.ServiceID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const bookingByIdempotencyKey = `-- name: BookingByIdempotencyKey :one
SELECT id, tenant_id, staff_id, service_id, customer_name, customer_email,
       starts_at, ends_at, status, idempotency_key, created_at
  FROM bookings
 WHERE tenant_id = $1 AND idempotency_key = $2
`

type BookingByIdempotencyKeyParams struct {
	TenantID       uuid.UUID
	IdempotencyKey string
}

func (q *Queries) BookingByIdempotencyKey(ctx context.Context, arg BookingByIdempotencyKeyParams) (Booking, error) {
	row := q.db.QueryRow(ctx, bookingByIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StaffID,
		&i.ServiceID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const cancelBooking = `-- name: CancelBooking :execrows
UPDATE bookings SET status = 'cancelled' WHERE id = $1
`

// Cancelling is status-blind, so a repeat cancel still reports one row.
func (q *Queries) CancelBooking(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelBooking, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertBooking = `-- name: InsertBooking :one
INSERT INTO bookings (tenant_id, staff_id, service_id, customer_name, customer_email,
                      starts_at, ends_at, status, idempotency_key)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, 'confirmed', $8)
ON CONFLICT (tenant_id, idempotency_key) DO NOTHING
RETURNING id, tenant_id, staff_id, service_id, customer_name, customer_email,
          starts_at, ends_at, status, idempotency_key, created_at
`

type InsertBookingParams struct {
	TenantID       uuid.UUID
	StaffID        uuid.UUID
	ServiceID      uuid.UUID
	CustomerName   string
	CustomerEmail  string
	StartsAt       time.Time
	EndsAt         time.Time
	IdempotencyKey string
}

func (q *Queries) InsertBooking(ctx context.Context, arg InsertBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, insertBooking,
		arg.TenantID,
		arg.StaffID,
		arg.ServiceID,
		arg.CustomerName,
		arg.CustomerEmail,
		arg.StartsAt,
		arg.EndsAt,
		arg.IdempotencyKey,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StaffID,
		&i.ServiceID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const lockActiveStaff = `-- name: LockActiveStaff :one
SELECT 1 AS visible FROM staff WHERE id = $1 AND active FOR UPDATE
`

// The write path locks the staff row before inserting, so concurrent bookings
// for one staff member queue instead of deadlocking on the exclusion
// constraint's index. A deactivated staff member is not lockable: a booking
// would otherwise be stored for somebody who no longer takes appointments.
func (q *Queries) LockActiveStaff(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, lockActiveStaff, id)
	var visible int32
	err := row.Scan(&visible)
	return visible, err
}
