// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeJob = `-- name: CompleteJob :execrows

UPDATE jobs
   SET status = 'done', locked_by = NULL, locked_until = NULL, updated_at = now()
 WHERE id = $1 AND locked_by = $2::text AND status = 'running'
`

type CompleteJobParams struct {
	ID       uuid.UUID
	WorkerID string
}

// Every transition is guarded by the lease the caller still holds: a job whose
// lease expired and was reclaimed by another worker matches nothing, and the
// caller logs that instead of fighting over the row.
func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeJob, arg.ID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deadLetterJob = `-- name: DeadLetterJob :execrows
UPDATE jobs
   SET status = 'dead', last_error = $1, locked_by = NULL, locked_until = NULL,
       updated_at = now()
 WHERE id = $2 AND locked_by = $3::text AND status = 'running'
`

type DeadLetterJobParams struct {
	Reason   pgtype.Text
	ID       uuid.UUID
	WorkerID string
}

func (q *Queries) DeadLetterJob(ctx context.Context, arg DeadLetterJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, deadLetterJob, arg.Reason, arg.ID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertBookingJob = `-- name: InsertBookingJob :execrows
INSERT INTO jobs (tenant_id, booking_id, kind, run_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, booking_id, kind) DO NOTHING
`

type InsertBookingJobParams struct {
	TenantID  uuid.UUID
	BookingID uuid.UUID
	Kind      string
	RunAt     time.Time
}

// The enqueue rides the booking's own transaction: a booking that committed
// always has its confirmation row, and a transaction that failed built neither.
// The fresh-insert path is the only caller, so the no-op conflict clause is a
// belt-and-braces guard on the unique (tenant, booking, kind) key.
func (q *Queries) InsertBookingJob(ctx context.Context, arg InsertBookingJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBookingJob,
		arg.TenantID,
		arg.BookingID,
		arg.Kind,
		arg.RunAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseJob = `-- name: ReleaseJob :execrows
UPDATE jobs
   SET status = 'ready', locked_by = NULL, locked_until = NULL,
       attempts = greatest(attempts - 1, 0), updated_at = now()
 WHERE id = $1 AND locked_by = $2::text AND status = 'running'
`

type ReleaseJobParams struct {
	ID       uuid.UUID
	WorkerID string
}

// The refund keeps a shutdown from spending a job's attempt budget: the claim
// incremented attempts, the handler never finished, so the claim is undone. A
// claim whose lease expired and moved on fails the guard and stays counted.
func (q *Queries) ReleaseJob(ctx context.Context, arg ReleaseJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseJob, arg.ID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryJob = `-- name: RetryJob :execrows
UPDATE jobs
   SET status = 'ready', run_at = $1, last_error = $2,
       locked_by = NULL, locked_until = NULL, updated_at = now()
 WHERE id = $3 AND locked_by = $4::text AND status = 'running'
`

type RetryJobParams struct {
	RunAt    time.Time
	Reason   pgtype.Text
	ID       uuid.UUID
	WorkerID string
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryJob,
		arg.RunAt,
		arg.Reason,
		arg.ID,
		arg.WorkerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
