// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	ActorUserID pgtype.UUID
	Action      string
	BookingID   pgtype.UUID
	ServiceID   pgtype.UUID
	StaffID     pgtype.UUID
	CreatedAt   time.Time
}

type AvailabilityRule struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	StaffID     uuid.UUID
	Weekday     int16
	StartMinute int32
	EndMinute   int32
	CreatedAt   time.Time
}

type Booking struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	StaffID        uuid.UUID
	ServiceID      uuid.UUID
	CustomerName   string
	CustomerEmail  string
	StartsAt       time.Time
	EndsAt         time.Time
	Status         string
	IdempotencyKey string
	CreatedAt      time.Time
}

type Job struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	BookingID   uuid.UUID
	Kind        string
	Status      string
	Attempts    int32
	RunAt       time.Time
	LockedBy    pgtype.Text
	LockedUntil pgtype.Timestamptz
	LastError   pgtype.Text
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PasswordResetToken struct {
	TokenHash []byte
	TenantID  uuid.UUID
	UserID    uuid.UUID
	ExpiresAt time.Time
	UsedAt    pgtype.Timestamptz
	CreatedAt time.Time
}

type Service struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	Name            string
	DurationMinutes int32
	BufferMinutes   int32
	PriceCents      int32
	CreatedAt       time.Time
	Active          bool
}

type Session struct {
	TokenHash []byte
	Data      []byte
	Expiry    time.Time
}

type Staff struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	Email     string
	Active    bool
	CreatedAt time.Time
}

type Tenant struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	Timezone  string
	CreatedAt time.Time
}

type TimeOff struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	StaffID   uuid.UUID
	StartsAt  time.Time
	EndsAt    time.Time
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Email        string
	PasswordHash string
	Role         string
	StaffID      pgtype.UUID
	CreatedAt    time.Time
}
