// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reset_tokens.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeResetToken = `-- name: ConsumeResetToken :one
UPDATE password_reset_tokens
   SET used_at = now()
 WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING user_id
`

// Single use is decided by the database, not by a read followed by a write:
// only the first concurrent caller finds a row to mark used.
func (q *Queries) ConsumeResetToken(ctx context.Context, tokenHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumeResetToken, tokenHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const deleteOpenResetTokens = `-- name: DeleteOpenResetTokens :exec
DELETE FROM password_reset_tokens
 WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) DeleteOpenResetTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOpenResetTokens, userID)
	return err
}

const insertResetToken = `-- name: InsertResetToken :exec
INSERT INTO password_reset_tokens (token_hash, tenant_id, user_id, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertResetTokenParams struct {
	TokenHash []byte
	TenantID  uuid.UUID
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) InsertResetToken(ctx context.Context, arg InsertResetTokenParams) error {
	_, err := q.db.Exec(ctx, insertResetToken,
		arg.TokenHash,
		arg.TenantID,
		arg.UserID,
		arg.ExpiresAt,
	)
	return err
}
