// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const insertService = `-- name: InsertService :one
INSERT INTO services (tenant_id, name, duration_minutes, buffer_minutes, price_cents)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertServiceParams struct {
	TenantID        uuid.UUID
	Name            string
	DurationMinutes int32
	BufferMinutes   int32
	PriceCents      int32
}

func (q *Queries) InsertService(ctx context.Context, arg InsertServiceParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertService,
		arg.TenantID,
		arg.Name,
		arg.DurationMinutes,
		arg.BufferMinutes,
		arg.PriceCents,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listServices = `-- name: ListServices :many
SELECT id, tenant_id, name, duration_minutes, buffer_minutes, price_cents, active
  FROM services
 ORDER BY name, id
`

type ListServicesRow struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	Name            string
	DurationMinutes int32
	BufferMinutes   int32
	PriceCents      int32
	Active          bool
}

func (q *Queries) ListServices(ctx context.Context) ([]ListServicesRow, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesRow{}
	for rows.Next() {
		var i ListServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.DurationMinutes,
			&i.BufferMinutes,
			&i.PriceCents,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setServiceActive = `-- name: SetServiceActive :execrows
UPDATE services SET active = $1 WHERE id = $2
`

type SetServiceActiveParams struct {
	Active bool
	ID     uuid.UUID
}

func (q *Queries) SetServiceActive(ctx context.Context, arg SetServiceActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setServiceActive, arg.Active, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateService = `-- name: UpdateService :execrows
UPDATE services
   SET name = $1,
       duration_minutes = $2,
       buffer_minutes = $3,
       price_cents = $4
 WHERE id = $5
`

type UpdateServiceParams struct {
	Name            string
	DurationMinutes int32
	BufferMinutes   int32
	PriceCents      int32
	ID              uuid.UUID
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateService,
		arg.Name,
		arg.DurationMinutes,
		arg.BufferMinutes,
		arg.PriceCents,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
