// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: staff.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const insertStaff = `-- name: InsertStaff :one
INSERT INTO staff (tenant_id, name, email)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertStaffParams struct {
	TenantID uuid.UUID
	Name     string
	Email    string
}

func (q *Queries) InsertStaff(ctx context.Context, arg InsertStaffParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertStaff, arg.TenantID, arg.Name, arg.Email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listStaff = `-- name: ListStaff :many
SELECT id, tenant_id, name, email, active
  FROM staff
 ORDER BY name, id
`

type ListStaffRow struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Name     string
	Email    string
	Active   bool
}

func (q *Queries) ListStaff(ctx context.Context) ([]ListStaffRow, error) {
	rows, err := q.db.Query(ctx, listStaff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaffRow{}
	for rows.Next() {
		var i ListStaffRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Email,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStaffActive = `-- name: SetStaffActive :execrows
UPDATE staff SET active = $1 WHERE id = $2
`

type SetStaffActiveParams struct {
	Active bool
	ID     uuid.UUID
}

func (q *Queries) SetStaffActive(ctx context.Context, arg SetStaffActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStaffActive, arg.Active, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStaff = `-- name: UpdateStaff :execrows
UPDATE staff SET name = $1, email = $2 WHERE id = $3
`

type UpdateStaffParams struct {
	Name  string
	Email string
	ID    uuid.UUID
}

func (q *Queries) UpdateStaff(ctx context.Context, arg UpdateStaffParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStaff, arg.Name, arg.Email, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
