// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const insertTenant = `-- name: InsertTenant :one
INSERT INTO tenants (id, slug, name, timezone)
VALUES ($1, $2, $3, $4)
ON CONFLICT (slug) DO NOTHING
RETURNING id
`

type InsertTenantParams struct {
	ID       uuid.UUID
	Slug     string
	Name     string
	Timezone string
}

func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertTenant,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Timezone,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
