// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1070
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

const htmxFile = "/static/htmx-2.0.4.min.js"

func Layout() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>Slotwise</title><script src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(htmxFile)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/adapters/web/views/layout.templ`, Line: 12, Col: 25}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" defer></script><style>\n  * { box-sizing: border-box; }\n  body {\n    margin: 0 auto;\n    max-width: 46rem;\n    padding: 1.5rem 1rem 3rem;\n    font: 16px/1.5 system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif;\n    color: #1a1a1a;\n    background: #fff;\n  }\n  h1 { font-size: 1.5rem; margin: 0 0 .5rem; }\n  h2 { font-size: 1.15rem; margin: 2rem 0 .5rem; }\n  p { margin: .5rem 0; }\n  form { margin: 1rem 0; }\n  label { display: block; font-weight: 600; font-size: .85rem; margin-bottom: .15rem; }\n  input { font: inherit; padding: .35rem .5rem; border: 1px solid #767676; border-radius: 4px; max-width: 100%; }\n  button { font: inherit; padding: .4rem .8rem; border: 1px solid #767676; border-radius: 4px; background: #f3f3f3; cursor: pointer; }\n  input:focus-visible, button:focus-visible, a:focus-visible { outline: 3px solid #1a5fb4; outline-offset: 2px; }\n  a { color: #1a5fb4; }\n  .error { border: 1px solid #b3261e; background: #fdecea; color: #7a1c16; padding: .6rem .8rem; border-radius: 4px; }\n  .notice { border: 1px solid #1b6e3c; background: #e8f5ec; color: #14532d; padding: .6rem .8rem; border-radius: 4px; }\n  .muted { color: #5f6368; }\n  table { width: 100%; border-collapse: collapse; margin: .75rem 0; }\n  th, td { border: 1px solid #c4c4c4; padding: .4rem .5rem; text-align: left; vertical-align: top; }\n  th { background: #f3f3f3; }\n  td form { margin: .25rem 0; }\n  .day { min-width: 7rem; }\n  .booking { border-left: 3px solid #1a5fb4; padding-left: .4rem; margin: .25rem 0; }\n  .booking.cancelled { border-left-color: #b3261e; color: #5f6368; text-decoration: line-through; }\n  .toolbar { display: flex; gap: .5rem; align-items: baseline; margin: .75rem 0; }\n  footer { margin-top: 3rem; padding-top: .75rem; border-top: 1px solid #e0e0e0; color: #5f6368; font-size: .85rem; }\n</style></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<footer>Slotwise — scheduling for small teams.</footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
